### ISSUE TITLE
Better error handling when 401 connecting to Foreman-API

### ISSUE THREAD

**Issue by eni23** [adfinis-sygroup/foreman-yml#23]
When using invalid credentials, the error message should be more verbose than:

```
ERROR: cannot connect to foreman-api
```

**Comment by JvdW** [comment]
Maybe a better message is needed but I think there is a real bug behind it.
I'm sure I have entered the correct credentials and I'm backed by production.log of foreman which shows the /apidoc/v2.json GET but I still get the error Cannot connect ot Foreman-API.
Using ipdb, first time for me, I see a syntax error passing by right after the apidoc/v2.json and then the above error.
I'm using Foreman-1.12.2/Centos7 and foreman-yml 0.0.2 cloned from here.

**Comment by karras** [comment]
I've replied to your foreman-users post, maybe you're only missing the apipie cache. Try to generate it with `# /usr/sbin/foreman-rake apipie:cache`. If it doesn't help let me try to reproduce it by quickly installing a new Foreman instance. :)

**Comment by pfitzmsn** [comment]
Was this ever fixed? I am having the same issue with 1.15 and a new build. (Default DB). but the `/usr/sbin/foreman-rake apipie:cache` doesn't fix the issue. thank you.

**Comment by pfitzmsn** [comment]
Please disregard above I used the default answer file for foreman and this tool now works must be something with the proxy and multiple networks that prevents some network traffic back to the host.

**Comment by sreejithap** [comment]
Hi, am trying to install foreman 1.15 and I get the same error could not connect to API. Port is open . And /usr/sbin/foreman-rake apipie:cache runs fine 
FYI.. i do have installed httpd- mod-passenger instead of ngnix- passenger and db is postgresql

**Comment by braggy** [comment]
I'm getting this error on a fresh install, would be good to know what the actual problem is!

**Comment by vruwink** [comment]
I'm seeing this error as well, on a clean install on CentOS7.  I've rerun foreman-rake apipie:cache to no avail.

**Comment by codeburster** [comment]
Getting same error on CentOS7.

**Comment by karras** [comment]
@vruwink / @codeburster I guess you're using Foreman 1.18 or 1.19, right? Can you please post your foreman-yml config?

Please also check /var/log/foreman/production.log.

**Comment by vruwink** [comment]
@karras yeah, I'm using the foreman-ansible code.  Believe it's version 1.19 foreman. I pretty much left all the defaults.
foreman_config.yml:

---
foreman:
  auth:
    url: "http://localhost:80"
    user: admin
    pass: foreman

  setting:
    - name: safemode_render
      value: false

edit:
Re-ran the ansible-playbook, and tailed production.log last few lines during the install are:
2018-10-25T16:52:01 [I|app|2f08c] Completed 200 OK in 74ms (Views: 67.6ms | ActiveRecord: 1.3ms)
2018-10-25T16:52:01 [I|app|] Started GET "/apidoc/v2.json" for 127.0.0.1 at 2018-10-25 16:52:01 -0500
2018-10-25T16:52:01 [I|app|720bf] Processing by Apipie::ApipiesController#index as JSON
2018-10-25T16:52:01 [I|app|720bf]   Parameters: {"version"=>"v2.json", "apipy"=>{}}
2018-10-25T16:52:01 [I|app|720bf] Sent file /usr/share/foreman/public/apipie-cache/apidoc/v2.json (0.1ms)
2018-10-25T16:52:01 [I|app|720bf] Completed 200 OK in 1ms (ActiveRecord: 0.0ms)

with the fail message on the ansible server:

TASK [foreman_yml : configure foreman with foreman-yml] *************************************************************
fatal: [hostname.redacted]: FAILED! => {"changed": true, "cmd": "foreman-yml /opt/foreman-yml/foreman_config.yml > /opt/foreman-yml/ansible.log", "delta": "0:00:11.217392", "end": "2018-10-25 16:52:02.517872", "msg": "non-zero return code", "rc": 1, "start": "2018-10-25 16:51:51.300480", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

**Comment by karras** [comment]
Thanks for staying tuned! I was able to reproduce the issue on a CentOS 7 VM using python2. So far I couldn't find the root cause but noticed that the issue doesn't occur when working within a virtualenv.

Can you quickly try that on your end?
```
# git clone https://github.com/adfinis-sygroup/foreman-yml/
# cd foreman-yml
# yum install python-virtualenv
# virtualenv .venv
# source .venv/bin/activate
# pip install .
```
Then run foreman-yml.

**Comment by vruwink** [comment]
@karras 
well, that seemed to work.  :) But only if I completely stepped outside of the foreman-ansible setup script.  I had to copy the foreman_config.yml from that attempt, and follow your directions above (clone foreman-yml, setup virtualenv etc).  In other words, do it completely from scratch.

So what does this mean for deploying foreman (sans Puppet)?  My ansible run for foreman-ansible shows:
ok=35   changed=7    unreachable=0    failed=1

**Comment by karras** [comment]
Project archived
