### ISSUE TITLE
Setting Puppet Master and Puppet CA in Hostgroups impossbile?

### ISSUE THREAD

**Issue by rauchrob** [adfinis-sygroup/foreman-yml#27]
It seems to be impossible to set the Puppet Master and/or Puppet CA in Hostgroups created with `foreman-yml`. How is it possible?

**Comment by karras** [comment]
I'm currently having a look at the `Add Hostgroups` option in the Foreman webinterface. Do you mean assigning Puppet classes?

So far we haven't concentrated on adding Puppet related settings because it was not needed. Thus some options may be missing.

**Comment by DanyC97** [comment]
@rauchrob curious, why do you need it? i thought this/ the other repo doesn't install anything related to puppet , am i wrong ?

**Comment by karras** [comment]
Project archived
