### ISSUE TITLE
Location and organization

### ISSUE THREAD

**Issue by Mandorath** [adfinis-sygroup/foreman-yml#31]
Is there a specific reason why locations and organizations are not part of the plugin?

If not, do you mind me adding the required functions within the code for configuring location and organizations? Additionaly i'd like to add the configuration of both to each object that can accept them.

**Comment by tongpu** [comment]
Currently foreman-yml is limited to the functionality we've been using during our project, and we're very much looking forward to contributions that extend it.

Feel free to add what you see fit and start a pull request.

**Comment by andreabettich** [comment]
The PR #50 will add this feature.

**Comment by karras** [comment]
Project archived
