### ISSUE TITLE
Host creation failure

### ISSUE THREAD

**Issue by Mandorath** [adfinis-sygroup/foreman-yml#35]
Hey,

I'm adding some extra functionalities including the option to specify location and organizations. Basically the script will ask if organization and/or locations are used and than enable these options. I'm running into a small problem when creating hosts though i've traced it to the following part of code and I'm wondering what it specifically does:
```python
 try:
                    fixif = {
                        'id':           fmh['interfaces'][0]['id'],
                        'managed':      'false',
                        'primary':      'true',
                        'provision':    'true'
                    }
                    fixhost = {
                        'interfaces_attributes':        [ fixif ],
                        'host_parameters_attributes':   host_params
                    }
                    try:
                        self.fm.hosts.update(fixhost, fmh['id'])
                        return fmh
                    except:
                        log.log(log.LOG_DEBUG, "An Error Occured when linking Host '{0}' (non-fatal)".format(hostc['name']))
                except:
pass
```
I've removed it in my test setup and I can't detect any changes, I'm assuming this was added to fix some kind of error that occured but I don't have any errors when I run foreman-yaml without it.

**Comment by Mandorath** [comment]
I've already found a fix for this. I've also found a way to add multiple interfaces based on a loop.

**Comment by karras** [comment]
Project archived
