### ISSUE TITLE
Install fails on CentOS 7.3.1611

### ISSUE THREAD

**Issue by duncaninnes** [adfinis-sygroup/foreman-yml#43]
The install instructions are short & sweet, but I can't get them to work on a clean CentOS 7.3.1611 system.  All updates have been applied and python2-pip-8.1.2-5.el7.noarch is installed to provide pip.

The result I get is:

[root@katello foreman-yml]# pip install .
Processing /root/foreman-yml
Collecting pyyaml (from foreman-yml==1.0.2)
  Using cached PyYAML-3.12.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/site-packages (from foreman-yml==1.0.2)
Collecting python-foreman (from foreman-yml==1.0.2)
  Using cached python-foreman-0.4.14.tar.gz
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-j7A5Zt/python-foreman/autosemver-0.2.4_-py2.7.egg
    Searching for dulwich
    Reading https://pypi.python.org/simple/dulwich/
    Best match: dulwich 0.16.3
    Downloading https://pypi.python.org/packages/9e/d7/8fb5b952ad14f27f7ab1bbe17db7860fe99c3c3e5d08de0bea3a161389a0/dulwich-0.16.3.tar.gz#md5=632280ffa88f732ba61ed320f7bb60aa
    Processing dulwich-0.16.3.tar.gz
    Writing /tmp/easy_install-YQ1swJ/dulwich-0.16.3/setup.cfg
    Running dulwich-0.16.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-YQ1swJ/dulwich-0.16.3/egg-dist-tmp-6KXWKV
    warning: no files found matching 'README.swift'
    warning: no files found matching 'HACKING'
    warning: no files found matching 'CONTRIBUTING'
    warning: no files found matching 'relicensing-apachev2.txt'
    unable to execute gcc: No such file or directory
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-j7A5Zt/python-foreman/setup.py", line 35, in <module>
        'Programming Language :: Python :: 3.4',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-j7A5Zt/python-foreman/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@katello foreman-yml]#

I have tried doing a pip install --upgrade pip, but this just results in a different error and a pip installation which I can't fix or amend as the pip upgrade has overwritten the RPM which the RPM database still thinks is valid.

**Comment by forzamehlano** [comment]
"unable to execute gcc: No such file or directory". 

You might want to check that gcc is installed on your system and on your path.

**Comment by duncaninnes** [comment]
Apologies, I rebuilt my Katello machine and forgot this step.  I still get a failure after installing gcc:

[root@katello ~]# rpm -qa | grep gcc
libgcc-4.8.5-11.el7.x86_64
[root@katello ~]# yum install gcc
Loaded plugins: fastestmirror
base                                                     | 3.6 kB     00:00     
centos-sclo-rh                                           | 2.9 kB     00:00     
centos-sclo-sclo                                         | 2.9 kB     00:00     
epel/x86_64/metalink                                     |  20 kB     00:00     
epel                                                     | 4.3 kB     00:00     
extras                                                   | 3.4 kB     00:00     
foreman                                                  | 2.9 kB     00:00     
foreman-plugins                                          | 2.9 kB     00:00     
katello                                                  | 3.7 kB     00:00     
katello-candlepin                                        | 3.7 kB     00:00     
katello-client                                           | 3.6 kB     00:00     
katello-pulp                                             | 3.7 kB     00:00     
puppetlabs-pc1                                           | 2.5 kB     00:00     
updates                                                  | 3.4 kB     00:00     
(1/8): centos-sclo-sclo/x86_64/primary_db                  | 145 kB   00:00     
(2/8): epel/x86_64/updateinfo                              | 756 kB   00:01     
(3/8): extras/7/x86_64/primary_db                          | 139 kB   00:00     
(4/8): puppetlabs-pc1/x86_64/primary_db                    | 109 kB   00:00     
(5/8): foreman-plugins/x86_64/primary_db                   |  87 kB   00:00     
(6/8): foreman/x86_64/primary_db                           | 175 kB   00:01     
(7/8): updates/7/x86_64/primary_db                         | 3.8 MB   00:04     
(8/8): epel/x86_64/primary_db                              | 4.6 MB   00:05     
Loading mirror speeds from cached hostfile
 * base: mirror.mhd.uk.as44574.net
 * epel: www.mirrorservice.org
 * extras: mirrors.coreix.net
 * updates: anorien.csc.warwick.ac.uk
Resolving Dependencies
--> Running transaction check
---> Package gcc.x86_64 0:4.8.5-11.el7 will be installed
--> Processing Dependency: cpp = 4.8.5-11.el7 for package: gcc-4.8.5-11.el7.x86_64
--> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.8.5-11.el7.x86_64
--> Processing Dependency: libmpfr.so.4()(64bit) for package: gcc-4.8.5-11.el7.x86_64
--> Processing Dependency: libmpc.so.3()(64bit) for package: gcc-4.8.5-11.el7.x86_64
--> Running transaction check
---> Package cpp.x86_64 0:4.8.5-11.el7 will be installed
---> Package glibc-devel.x86_64 0:2.17-157.el7_3.1 will be installed
--> Processing Dependency: glibc-headers = 2.17-157.el7_3.1 for package: glibc-devel-2.17-157.el7_3.1.x86_64
--> Processing Dependency: glibc-headers for package: glibc-devel-2.17-157.el7_3.1.x86_64
---> Package libmpc.x86_64 0:1.0.1-3.el7 will be installed
---> Package mpfr.x86_64 0:3.1.1-4.el7 will be installed
--> Running transaction check
---> Package glibc-headers.x86_64 0:2.17-157.el7_3.1 will be installed
--> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-157.el7_3.1.x86_64
--> Processing Dependency: kernel-headers for package: glibc-headers-2.17-157.el7_3.1.x86_64
--> Running transaction check
---> Package kernel-headers.x86_64 0:3.10.0-514.10.2.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package             Arch        Version                     Repository    Size
================================================================================
Installing:
 gcc                 x86_64      4.8.5-11.el7                base          16 M
Installing for dependencies:
 cpp                 x86_64      4.8.5-11.el7                base         5.9 M
 glibc-devel         x86_64      2.17-157.el7_3.1            updates      1.1 M
 glibc-headers       x86_64      2.17-157.el7_3.1            updates      668 k
 kernel-headers      x86_64      3.10.0-514.10.2.el7         updates      4.8 M
 libmpc              x86_64      1.0.1-3.el7                 base          51 k
 mpfr                x86_64      3.1.1-4.el7                 base         203 k

Transaction Summary
================================================================================
Install  1 Package (+6 Dependent packages)

Total download size: 29 M
Installed size: 60 M
Is this ok [y/d/N]: y
Downloading packages:
(1/7): glibc-headers-2.17-157.el7_3.1.x86_64.rpm           | 668 kB   00:01     
(2/7): glibc-devel-2.17-157.el7_3.1.x86_64.rpm             | 1.1 MB   00:03     
(3/7): cpp-4.8.5-11.el7.x86_64.rpm                         | 5.9 MB   00:06     
(4/7): libmpc-1.0.1-3.el7.x86_64.rpm                       |  51 kB   00:00     
(5/7): mpfr-3.1.1-4.el7.x86_64.rpm                         | 203 kB   00:00     
(6/7): kernel-headers-3.10.0-514.10.2.el7.x86_64.rpm       | 4.8 MB   00:05     
(7/7): gcc-4.8.5-11.el7.x86_64.rpm                         |  16 MB   00:13     
--------------------------------------------------------------------------------
Total                                              2.1 MB/s |  29 MB  00:13     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : mpfr-3.1.1-4.el7.x86_64                                      1/7 
  Installing : libmpc-1.0.1-3.el7.x86_64                                    2/7 
  Installing : cpp-4.8.5-11.el7.x86_64                                      3/7 
  Installing : kernel-headers-3.10.0-514.10.2.el7.x86_64                    4/7 
  Installing : glibc-headers-2.17-157.el7_3.1.x86_64                        5/7 
  Installing : glibc-devel-2.17-157.el7_3.1.x86_64                          6/7 
  Installing : gcc-4.8.5-11.el7.x86_64                                      7/7 
  Verifying  : glibc-headers-2.17-157.el7_3.1.x86_64                        1/7 
  Verifying  : glibc-devel-2.17-157.el7_3.1.x86_64                          2/7 
  Verifying  : mpfr-3.1.1-4.el7.x86_64                                      3/7 
  Verifying  : kernel-headers-3.10.0-514.10.2.el7.x86_64                    4/7 
  Verifying  : libmpc-1.0.1-3.el7.x86_64                                    5/7 
  Verifying  : gcc-4.8.5-11.el7.x86_64                                      6/7 
  Verifying  : cpp-4.8.5-11.el7.x86_64                                      7/7 

Installed:
  gcc.x86_64 0:4.8.5-11.el7                                                     

Dependency Installed:
  cpp.x86_64 0:4.8.5-11.el7                                                     
  glibc-devel.x86_64 0:2.17-157.el7_3.1                                         
  glibc-headers.x86_64 0:2.17-157.el7_3.1                                       
  kernel-headers.x86_64 0:3.10.0-514.10.2.el7                                   
  libmpc.x86_64 0:1.0.1-3.el7                                                   
  mpfr.x86_64 0:3.1.1-4.el7                                                     

Complete!
[root@katello ~]# rpm -qa | grep gcc
libgcc-4.8.5-11.el7.x86_64
gcc-4.8.5-11.el7.x86_64
[root@katello ~]# cd foreman-yml/
[root@katello foreman-yml]# pip install .
Processing /root/foreman-yml
Collecting pyyaml (from foreman-yml==1.0.2)
  Using cached PyYAML-3.12.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/site-packages (from foreman-yml==1.0.2)
Collecting python-foreman (from foreman-yml==1.0.2)
  Downloading python-foreman-0.4.18.tar.gz (257kB)
    100% |████████████████████████████████| 266kB 897kB/s 
    Complete output from command python setup.py egg_info:
    zip_safe flag not set; analyzing archive contents...
    
    Installed /tmp/pip-build-GX3bIp/python-foreman/autosemver-0.4.0_-py2.7.egg
    Searching for dulwich
    Reading https://pypi.python.org/simple/dulwich/
    Best match: dulwich 0.17.1
    Downloading https://pypi.python.org/packages/dd/59/257398c30e0249a7212bc7c22980676e1cc7798e4101639d1d80f933cb4f/dulwich-0.17.1.tar.gz#md5=709ce14bcae8ef76bf3594b3ae975fd5
    Processing dulwich-0.17.1.tar.gz
    Writing /tmp/easy_install-0oKyGs/dulwich-0.17.1/setup.cfg
    Running dulwich-0.17.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-0oKyGs/dulwich-0.17.1/egg-dist-tmp-4PmQco
    dulwich/_objects.c:21:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-GX3bIp/python-foreman/setup.py", line 35, in <module>
        'Programming Language :: Python :: 3.4',
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 618, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 862, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 874, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 339, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 653, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1118, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-GX3bIp/python-foreman/
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@katello foreman-yml]#

**Comment by forzamehlano** [comment]
I think you're now missing the python headers which are usually provided by the python-devel package.

**Comment by duncaninnes** [comment]
That's it. Would it be possible to include something in the README for idiot admins like myself who aren't used to building python scripts from scratch?  Something like:

"Note: RHEL and CentOS users should ensure gcc and python-devel packages are installed"

**Comment by andreabettich** [comment]
@duncaninnes , I'll add a note to the README.

**Comment by andreabettich** [comment]
Added note in PR #47
