### ISSUE TITLE
Migrate documention to sphinx

### ISSUE THREAD

**Issue by karras** [adfinis-sygroup/foreman-yml#7]
Please migrate the documentation to rst / sphinx and publish it on our docs server.

**Comment by eni23** [comment]
IMHO sphinx would only make sense, if there were more than one page documentation and if this is an internal project.
We should keep everything on github for public ones. Thus, we would have the problem that we currently cannot build GitHub-Projects on our CI.

If the docs get more complex we could build them into GH-Pages or readthedocs. But we should not host such docs on our internal server..

**Comment by karras** [comment]
Project archived
